recipes/gcc/recipe.sh
recipes/gnu-binutils/recipe.sh

Striping crt* was causing issues.

Strip only executables, not libraries

---

recipes/ca-certificates/recipe.sh

This should fix the jenkins failure.

Correct ca-certificates recipe

---

.gitignore
cook.sh
recipes/cargo/recipe.sh
recipes/openssl/recipe.sh

I think this method should work alright.
Fixes #38.

System for compile-time dependencies; use for openssl

---

cook.sh

That fix I'm reverting probably should work as well, so that method can be used if it's preferred.

Fix repo.sh call for build depends

---

recipes/pastel/recipe.sh

It still won't find the resources due to https://github.com/robbycerantola/pastel/issues/2, but this should fix build errors.

Fix pastel recipe; add 'mkdir'

---

recipes/gcc/recipe.sh

Build gcc with C++ support

---

recipes/extrautils/recipe.sh

See https://github.com/redox-os/extrautils/pull/26

Make extrautils have xz as a build depend

---

recipes/ncurses/01-config-sub.patch
recipes/ncurses/recipe.sh

Depends on https://github.com/redox-os/newlib/pull/57.

Add recipe for ncurses

---

recipes/readline/01-config-sub.patch
recipes/readline/recipe.sh

Add recipe for readline

---

recipes/curl/01-no-nonblock.patch
recipes/curl/02-threaded-resolver-fix.patch
recipes/curl/recipe.sh

Depends on https://github.com/redox-os/newlib/pull/60.

Use release tarball for curl, with a couple patches

---

recipes/perl/perl.patch
recipes/perl/recipe.sh

Recipe for perl

---

recipes/autoconf/recipe.sh
recipes/automake/recipe.sh
recipes/perl/perl.patch
recipes/perl/recipe.sh

I don't know why it's not properly detecting functions like this...

A couple fixes for perl, and initial recipes for automake and autoconf

---

.gitmodules
cook.sh

Add man pages using docgen when possible

Add man pages

---

recipes/prboom/01_redox.patch
recipes/prboom/recipe.sh
recipes/sdl/01_orbital.patch
recipes/sdl/recipe.sh

It starts up, but only shows a blank screen.
Also brings in the sdl port from the libc repo.

Add recipe for PrBoom. It almost runs doom!

---

recipes/fd/recipe.sh

We just upstreamed Redox support for `fd`.
I've tested and it seems to be working like a charm \o/

Recipe for fd.

---

recipes/xz/recipe.sh

The url https://tukaani.org seems to be down.

Fix xz's recipe

---

recipes/mdp/recipe.sh

This PR adds a recipe for `mdp`, command-line based markdown presentation tool: https://github.com/visit1985/mdp
It has some [rendering issues](https://imgur.com/a/ORA7u) but apart from that it works well.

Add mdp recipe

---

recipes/nulld/recipe.sh
recipes/zerod/recipe.sh

This is needed for redox-os/kernel#67.

Add recipes for nulld and zerod

---

recipes/netsurf/01_redox.patch
recipes/netsurf/recipe.sh
recipes/newlib/recipe.sh

This PR adds a recipe for the NetSurf web browser.
Screenshot: https://i.imgur.com/4F7ajYi.png
**What doesn't work yet:**
* HTTPS
* Compressed HTTP responses
* JPG and PNG images
* JavaScript
* TrueType fonts
* Mouse wheel
**Known issues:**
* Crash on exit
* Some keys produces NULL characters in the address field
* Double mouse cursors
**Testing:**
Random websites I used for testing (and more or less should work):
* http://www.netsurf-browser.org/
* http://microkernel.info/
* http://www.osnews.com/
* http://httpbin.org/

Add netsurf recipe

---

recipes/sdl/01_orbital.patch

sdl: Implement SDL_RESIZABLE and SDL_WM_SetCaption

---

recipes/sdl/01_orbital.patch

Do not free the pixel buffer after it's unmapped.
Part of #126

sdl: Fix page fault on SDL_Quit

---

recipes/freetype/recipe.sh
recipes/netsurf/01_redox.patch
recipes/netsurf/recipe.sh

netsurf: Enable freetype support

---

recipes/freetype/recipe.sh

Fixes a build issue reported on the chat server

Add libpng build dependency to freetype

---

recipes/netsurf/01_redox.patch

We can't miss this important opportunity to advertise/confuse website admins. :laughing:

Include "Redox" in netsurf user agent

---

recipes/netsurf/recipe.sh
recipes/orbital/recipe.sh
recipes/orbterm/recipe.sh
recipes/orbutils/recipe.sh
recipes/pastel/recipe.sh
recipes/periodictable/recipe.sh
recipes/pixelcannon/recipe.sh
recipes/rs-nes/recipe.sh
recipes/rust64/recipe.sh
recipes/rustual-boy/recipe.sh

And also make Orbital depend on the orbdata package.

Add Orbital as a runtime dependency for the GUI apps

---

recipes/lci/recipe.sh

I'm not sure I did this correctly, but I thought it's very extremely important to have a LOLCODE interpreter in redox ¯\\\_(ツ)_/¯

Add LOLCODE recipe

---

cook.sh
recipes/termplay/recipe.sh

Sorry, I messed up. I've now tested it and it works.
Added some informational messages to cook.sh while I'm at it so it's harder to miss in the future.

Fix termplay recipe (sorry)

---

recipes/ffmpeg/recipe.sh

Announcement: http://ffmpeg.org/index.html#pr4.0
The patches from version 3.4 did not require any changes.

Update ffmpeg to 4.0

---

recipes/sdl/02_timers.patch
recipes/sdl/recipe.sh

Some code had to be commented out due to missing newlib symbols but it's complete enough for PrBoom.

Enable SDL timers

---

recipes/ttf-hack/recipe.sh

Add ttf-hack recipe

---

recipes/ncdu/recipe.sh

This doesn't actually work that well, although I think that might be ncurses being buggy on redox in general. Vim is also acting a little weird...

Add ncdu recipe

---

recipes/netsurf/01_redox.patch
recipes/prboom/01_redox.patch
recipes/sdl/01_orbital.patch

This PR also removes the alpha handling hacks I temporarily added to NetSurf and PrBoom.

sdl: Fix alpha handling

---

recipes/openttd/01_redox.patch
recipes/openttd/recipe.sh

Initial port of OpenTTD. https://i.imgur.com/hKsPmlD.png
**Testing:**
* Install the [OpenGFX](https://www.openttd.org/en/download-opengfx) graphics set manually to `~/.openttd/baseset/opengfx-X.X.X`.
* `$ /games/openttd`

Add openttd recipe

---

recipes/openttd/recipe.sh

It fixes the background of the menu screen.

openttd: Enable LZMA

---

recipes/dosbox/01_redox.patch
recipes/dosbox/recipe.sh
recipes/sdl/03_cdrom.patch
recipes/sdl/recipe.sh

Video, mouse, r/w mounting folders, config file management works with small glitches around. Keyboard input doesn't work properly yet, dosbox incorrectly shifts the keycodes around. The `autoxec.bat` section of the config file could be used to run commands until I fix that bug.

Add dosbox recipe

---

recipes/dosbox/01_redox.patch

This PR implements a fix I mentioned in this comment: https://github.com/redox-os/cookbook/pull/151#issuecomment-386442518

dosbox: Fix keyboard input

---

recipes/gigalomania/01_makefile.patch
recipes/gigalomania/02_stdafx.patch
recipes/gigalomania/03_image.patch
recipes/gigalomania/04_sound.patch
recipes/gigalomania/05_game.patch
recipes/gigalomania/06_game_cpp.patch
recipes/gigalomania/07_gamestate_cpp.patch
recipes/gigalomania/recipe.sh
recipes/sdl_image/01_redox.patch
recipes/sdl_image/recipe.sh
recipes/sdl_mixer/01_redox.patch
recipes/sdl_mixer/recipe.sh

I added gigalomania (megalomania clone) to recipes requiring sdl_image and sdl_mixer as dependencies:
- sdl_image supports png and jpeg images via libpng and libjpeg
- sdl_mixer mp3 disabled

added gigalomania (megalomania clone) + sdl_image + sdl_mixer

---

recipes/libsodium/recipe.sh

libsodium recipe

---

recipes/miniserve/recipe.sh

Demo of actix-web running on redox

Add miniserve
