redox-os/cookbook

cook.sh, update-all.sh, update-packages.sh
Something like this is necessary in order for the cookbook to replace the Makefiles in the `redox` repo.
=> Add update-all.sh script to rebuild only out of date packages

cook.sh
Cargo searches parent directories for .cargo, so this is unnecessary.
=> Do not copy .cargo and libc-artifacts

cook.sh, recipes/gnu-make/recipe.sh
This is the same loop I originally added in #4, but moved to prepare. It could instead be handled by the recipe, but I think this is generally useful enough to handle in `cook.sh`.
Fixes #14.
=> Handle patches in prepare

cook.sh
We don't want the package to potentially have artifacts from a prior
build.
=> Make stage call unstage

recipes/gcc/recipe.sh
I hadn't tested this properly since I didn't want to wait for a full gcc build. This should fix the error on Jenkins.
=> Correction to gcc recipe

.gitignore, config.sh
I don't know what logic (if any) we need to add to handle updates to Rust
=> Set $XARGO_HOME to build std et al only once

cook.sh
At the moment, this changes nothing, but I think this is a much better way to specify the target that at build time.
=> Pass --target to pkg

recipes/rustual-boy/recipe.sh
This pull request adds a recipe for [Rustual Boy](https://github.com/emu-rs/rustual-boy), a Virtual Boy video game emulator. Some minimal changes had to be made to get it compile and run: I updated some dependencies and added a temporary null audio driver.
[Screenshot](https://user-images.githubusercontent.com/1627292/27997060-6c23aa3c-64f0-11e7-9b57-f74d9f3b450b.png)
=> Add rustual-boy recipe

config.sh, repo.sh
The cookbook scripts assume they have GNU utilities 
available this causes problems in macOS which has an
BSD userland. With these changes we will use the GNU
`find` and `stat` installed by the now modified boostrap
script on https://github.com/redox-os/redox/pull/995.
**Details**
- Using `find` from Homebrew/MacPorts `findutils` package on macOS.
- Using `stat` from Homebrew/MacPorts `coreutils` package on macOS.
**Dependencies**
https://github.com/redox-os/redox/pull/995.
=> Detecting find and stat from Homebrew/MacPorts on macOS

recipes/patch/02-no-chown.patch
Redox doesn't seem to provide chown currently. I was just going to implement that, since it seems simple enough, but it required an extra argument, and thus a new value added to `Packet`, and when I tried that it seemed to break the ABI. That system call obviously needs to be added anyway, but this patch will make patch work for now (along with https://github.com/redox-os/redoxfs/pull/32 and https://github.com/redox-os/newlib/pull/55).
=> Patch patch not to call chown

recipes/uutils/recipe.sh
Not in our coreutils:
- expr
- install
- mktemp
Replaces version in our coreutils (I'll send a PR to remove them)
- chmod—support format like `+x`
- env—in addition to printing the environment, can run a command with an environment
- ls—several features, what I needed was sorting (by time)
=> Add symlinks to uutils package

recipes/ncurses/recipe.sh
This PR fixes #70, by exporting a CPPFLAG variable that is required for compilation.
Apparently, it's a common issue with compiling `ncurses`: https://trac.sagemath.org/ticket/19762.
=> Fix ncurses failing to compile.

Xargo.toml
Depends on https://github.com/rust-lang/rust/pull/43635 (without which this will presumably break builds).
=> Enable 'backtrace' feature in libstd, to allow backtraces

cook.sh
With https://github.com/redox-os/cookbook/pull/58 (which should be fine to merge now, since the backtrace PR was merged into upstream rust-lang/rust), this allows Rust backtraces, including line numbers.
=> Add --debug argument to cook.sh to build in debug mode, unstripped

recipes/ffmpeg/ffmpeg.patch, recipes/ffmpeg/recipe.sh
It seems to work but it has some yet unsolved issues:
* Complains about `unimplemented: select()` when running. Those messages can be dismissed by pressing the return key.
* Network support had to be disabled due to some missing symbols (`getsockopt`, `SO_REUSEADDR`, `SO_ERROR`)
Audio decoding can be tested the following way:
```
$ ffmpeg -i /tmp/softwares_salvation.webm -ar 44100 -vn -acodec pcm_s16le -f s16le temp.raw
$ sudo dd if=temp.raw of=audio: bs=16384 count=-1
```
=> Add ffmpeg recipe

recipes/ffmpeg/recipe.sh
=> ffmpeg: Switch to a working release branch, fix hardcoded arch

cook.sh, recipes/curl/recipe.sh, recipes/gcc/recipe.sh, recipes/rust/recipe.sh
A variable called DEPENDS in recipes contains the runtime dependency information for packages. These get added to the package during tarring.
=> Add dependency info to packages

recipes/vttest/recipe.sh, recipes/vttest/vttest.patch
This PR adds a recipe for [`vttest`](http://invisible-island.net/vttest/), a VT100-style terminal test program. It might be useful for discovering bugs in `ransid` and `orbterm`.
=> Add vttest recipe

README.md
- whitespace cleanup
- add gentoo docs (note: the `PREFIX` stuff is dependent on redox-os/libc#42)
=> Add documentation for Gentoo Linux

recipes/vttest/recipe.sh
Using the last patch date as the version number because of the current maintainer states the following on his [website](http://invisible-island.net/vttest/): 
> I changed the version number to 2.0 in the initial release, in 1996, and went up to 2.7 shortly after. Since then, the patch-date is the effective version number.
=> vttest: Add recipe version

recipes/generaluser-gs/recipe.sh, recipes/timidity/recipe.sh
This PR adds recipes for two new packages, `generaluser-gs` and `timidity`. GeneralUser GS has [a custom license](https://github.com/xTibor/redox-generaluser-gs/blob/master/LICENSE.txt) but it's free, permissive and encourages redistribution.
Copypasta for quick testing:
```
sudo pkg install generaluser-gs timidity
```
```
wget -O test.mid https://github.com/ShinkoNet/shinkonet.github.io/raw/master/MIDIArchive/IshukanCommunication.mid
```
```
sudo timidity -OR test.mid
```
=> Add TiMidity++ and GeneralUser GS

recipes/git/recipe.sh
Git requires this package to be able to work over HTTPS.
=> Add ca-certificates dependency for git

recipes/ncursesw/01-config-sub.patch, recipes/ncursesw/recipe.sh, recipes/terminfo/recipe.sh, recipes/vim/recipe.sh
This PR introduces the following changes:
* Adds a new `ncursesw` package. It enables ncurses apps that require UTF-8 support to build.
* Removes the `terminfo` related files from the `ncurses` package. They are unnecessary there after the introduction of the `terminfo` package. They could also cause some clash between the `ncurses` and `ncursesw` packages.
* The `tabset` files has been added to the `terminfo` package and it required some path changes to the `terminfo` recipe.
* Added `terminfo` runtime deps where I think it's required.
=> Add ncursesw recipe, terminfo changes

recipes/logd/recipe.sh
The logd recipe was missing, preventing me from building. Now I can build again! redox-os/redox#1142
=> Added logd recipe.

recipes/userutils/recipe.sh
Alright, this should re-implement `whoami` as a link to id, depending on  redox-os/userutils/pull/32
=> Link whoami to id; Depends redox-os/userutils/#32

recipes/netsurf/01_redox.patch
The //TRANSLIT iconv extension doesn't seem to be supported by newlib.
Some good news: NetSurf is now able to log into GitHub and open pull requests. Like this one.
=> netsurf: Fix HTML forms

recipes/prboom/01_redox.patch
Depends on #142. This PR fixes the PrBoom port, making it playable: https://youtu.be/-wwwYIqfQik
There are some small issues like the lack of sound or no mouse capture but apart from those it works flawlessly.
**Testing:**
<code>user:~# /games/prboom -vidmode 32 -iwad [something.wad](http://doomgod.com/wads/iwads/)</code>
=> Fix prboom port

recipes/liborbital/recipe.sh, recipes/netsurf/recipe.sh, recipes/prboom/recipe.sh, recipes/sdl/01_orbital.patch, recipes/sdl/recipe.sh
This PR refactors the SDL port to use my new cbindgen-based Orbital client library, liborbital: https://github.com/xTibor/liborbital
After this change the functionality of the SDL port should remain the same, without any new (known) bugs or bugfixes.
If you find this PR okay, I could transfer that repo above to the Redox org as well.
=> Refactor SDL to use liborbital

recipes/sdl/01_orbital.patch
This PR fixes the keyboard input in OpenTTD (alphanumerical keys didn't work). The NetSurf bug that was the reason I uncommented that line is also no longer reproducible.
=> sdl: Revert unicode fix

recipes/libpng/recipe.sh, recipes/xz/recipe.sh
For some reason I couldn't compile without these.
I have no idea why they're not readable by default on my system,
and this probably isn't the best solution.
This is a hack.
Feel free to close this PR if it doesn't feel like the right solution!
=> Fix some weird permission issues

recipes/libsodium/random.patch
This stops libsodium from aborting on initialization
=> Patch libsodium randbytes
